name       : seahorse
version    : 3.32.1
release    : 12
source     :
    - https://download.gnome.org/sources/seahorse/3.32/seahorse-3.32.1.tar.xz : c69dcb2d3f433440d19bac3dec40c1a2a4de22f408003a543046f618a17a02da
license    : GPL-2.0-only
summary    : GNOME encryption key and password manager
component  : desktop.gnome
description: |
    Seahorse is a GNOME application for managing encryption keys and passwords in the GnomeKeyring. There's also a collection of plugins that integrate seahorse with nautilus, gedit and other places for encryption, decryption and other operations.
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(p11-kit-1)
    - pkgconfig(pwquality)
    - gnupg
    - gpgme-devel
    - itstool
    - libassuan-devel
    - openssh
    - vala
rundeps    :
    - gnupg
    - openssh
setup      : |
    %patch -p1 < $pkgfiles/gkr-Use-0-on-empty-flags.patch
    %meson_configure -Dkey-sharing=false -Dldap-support=false
build      : |
    %ninja_build
install    : |
    %ninja_install
