name       : seahorse
version    : 3.14.1
release    : 3
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/seahorse/3.14/seahorse-3.14.1.tar.xz : 092a890982fa594da8a384f156b961392f69ce5d9518a9801035e6deb1f05e93
license    : GPL-2.0
summary    : GNOME encryption key and password manager
description: |
    Seahorse is a GNOME application for managing encryption keys and passwords in the GnomeKeyring. There's also a collection of plugins that integrate seahorse with nautilus, gedit and other places for encryption, decryption and other operations.
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - gnupg
    - gpgme-devel
    - itstool
    - libassuan-devel
    - openssh
rundeps :
    - gnupg
    - openssh
setup      : |
    %configure --disable-valac
build      : |
    %make
install    : |
    %make_install
