name       : seahorse
version    : '42.0'
release    : 23
source     :
    - https://download.gnome.org/sources/seahorse/42/seahorse-42.0.tar.xz : c50cacebf8de7a7e2e5f1dae0b98232114741296abe8d543e3923d62a153d630
license    : GPL-2.0-only
summary    : GNOME encryption key and password manager
component  : desktop.gnome
description: |
    Seahorse is a GNOME application for managing encryption keys and passwords in the GnomeKeyring. There's also a collection of plugins that integrate seahorse with nautilus, gedit and other places for encryption, decryption and other operations.
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gpgme)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libassuan)
    - pkgconfig(libhandy-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(p11-kit-1)
    - pkgconfig(pwquality)
    - gnupg
    - gpgme-devel
    - itstool
    - libassuan-devel
    - openldap-devel
    - openssh
    - vala
rundeps    :
    - gnupg
    - openssh
setup      : |
    %meson_configure -Dkey-sharing=false -Dldap-support=true
build      : |
    %ninja_build
install    : |
    %ninja_install
