name       : seahorse
version    : 3.20.0
release    : 9
source     :
    - git|https://git.gnome.org/browse/seahorse : fb6fb6f69b4339eb53bfe3a60e9d192a80bec58e
license    : GPL-2.0-only
summary    : GNOME encryption key and password manager
component  : desktop.gnome
description: |
    Seahorse is a GNOME application for managing encryption keys and passwords in the GnomeKeyring. There's also a collection of plugins that integrate seahorse with nautilus, gedit and other places for encryption, decryption and other operations.
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - gnupg
    - gpgme-devel
    - itstool
    - libassuan-devel
    - openssh
    - vala
rundeps    :
    - gnupg
    - openssh
setup      : |
    %meson_configure -Dkey-sharing=false -Dldap-support=false
build      : |
    %ninja_build
install    : |
    %ninja_install
