name       : seahorse
version    : '43.0'
release    : 24
source     :
    - https://download.gnome.org/sources/seahorse/43/seahorse-43.0.tar.xz : 5b1d1bfba74f3658227f3c82e296f330dd0fcd1ef4636b6a218228fee5ea832d
license    : GPL-2.0-only
summary    : GNOME encryption key and password manager
component  : desktop.gnome
description: |
    Seahorse is a GNOME application for managing encryption keys and passwords in the GnomeKeyring. There's also a collection of plugins that integrate seahorse with nautilus, gedit and other places for encryption, decryption and other operations.
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gpgme)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libassuan)
    - pkgconfig(libhandy-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(p11-kit-1)
    - pkgconfig(pwquality)
    - desktop-file-utils
    - gnupg
    - gpgme-devel
    - itstool
    - libassuan-devel
    - openldap-devel
    - openssh
    - vala
rundeps    :
    - gnupg
    - openssh
setup      : |
    %meson_configure -Dkey-sharing=false -Dldap-support=true
build      : |
    %ninja_build
install    : |
    %ninja_install
