name       : seahorse
version    : 3.20.0
release    : 6
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/seahorse/3.20/seahorse-3.20.0.tar.xz : e2b07461ed54a8333e5628e9b8e517ec2b731068377bf376570aad998274c6df
license    : GPL-2.0
summary    : GNOME encryption key and password manager
description: |
    Seahorse is a GNOME application for managing encryption keys and passwords in the GnomeKeyring. There's also a collection of plugins that integrate seahorse with nautilus, gedit and other places for encryption, decryption and other operations.
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - gnupg
    - gpgme-devel
    - itstool
    - libassuan-devel
    - openssh
rundeps    :
    - gnupg
    - openssh
setup      : |
    %configure --disable-valac
build      : |
    %make
install    : |
    %make_install
